name: Validate

on:
  push:
    branches: ["*"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm 8
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i --no-save

      - name: Build
        run: pnpm run build

      - name: Run Tests
        run: pnpm run test

      - name: Run Code Lint
        continue-on-error: true
        run: pnpm run lint

      - name: Run Code Style Lint
        continue-on-error: true
        run: pnpm run lint:style
